// #Misfits Add - Door Logs tab for admin menu
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Misfits.Administration.UI.Tabs;

[GenerateTypedNameReferences]
public sealed partial class DoorLogsTab : Control
{
    public DoorLogsTab()
    {
        RobustXamlLoader.Load(this);

        OpenDoorLogsButton.Text = GetLocalizedOrFallback(
            "misfits-door-logs-tab-open-btn",
            "Open Door Logs");
        OpenDoorLogsDescription.Text = GetLocalizedOrFallback(
            "misfits-door-logs-tab-open-desc",
            "View the door destruction log - which doors were destroyed and by whom.");
    }

    /// <summary>
    /// Returns a localized string or a fallback if the locale key is missing.
    /// </summary>
    private static string GetLocalizedOrFallback(string key, string fallback)
    {
        var loc = IoCManager.Resolve<ILocalizationManager>();
        if (loc.TryGetString(key, out var localized))
            return localized;
        return fallback;
    }
}
