using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Shared._Nuclear14.AutodocSirius;
using Content.Shared.FixedPoint;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;

namespace Content.Client._Nuclear14.AutodocSirius;

[GenerateTypedNameReferences]
public sealed partial class SiriusAutodocWindow : DefaultWindow
{
    private static readonly ISawmill _sawmill = Logger.GetSawmill("autodoc");

    private static readonly Color ColorMinor = Color.FromHex("#33FF33");
    private static readonly Color ColorModerate = Color.FromHex("#FFAA33");
    private static readonly Color ColorSevere = Color.FromHex("#FF5533");
    private static readonly Color ColorCritical = Color.FromHex("#FF3333");
    private static readonly Color ColorDim = Color.FromHex("#1a5c1a");
    private static readonly Color ColorActive = Color.FromHex("#33FF33");
    private static readonly Color ColorInactive = Color.FromHex("#3a5c3a");

    private readonly Dictionary<string, string> _damageDisplayNames = new()
    {
        { "Blunt", "PHYSICAL" },
        { "Slash", "LACERATION" },
        { "Piercing", "PUNCTURE" },
        { "Heat", "THERMAL" },
        { "Cold", "CRYOGENIC" },
        { "Shock", "ELECTRICAL" },
        { "Caustic", "CHEMICAL" },
        { "Radiation", "RADIATION" },
        { "Bloodloss", "BLOOD LOSS" },
        { "Asphyxiation", "ASPHYXIA" },
        { "Toxin", "TOXIN" },
        { "Genetic", "GENETIC" },
        { "Cellular", "CELLULAR" }
    };

    public event Action<AutodocUiButton>? OnAutodocButton;

    public SiriusAutodocWindow()
    {
        RobustXamlLoader.Load(this);
        Title = "SIRIUS MD-3 - AUTODOC";

        ApplyBackgroundStyles();
        WireButtons();
        SetInitialButtonStates();
        OnClose += () => OnAutodocButton?.Invoke(AutodocUiButton.Close);
    }

    private void ApplyBackgroundStyles()
    {
        var darkBg = new StyleBoxFlat(Color.FromHex("#0a0a0a"));
        var brightLine = new StyleBoxFlat(Color.FromHex("#1a5c1a"));
        var dimLine = new StyleBoxFlat(Color.FromHex("#0f3d0f"));
        SepTop.PanelOverride = brightLine;
        SepMid1.PanelOverride = dimLine;
        SepMid2.PanelOverride = dimLine;
        SepMid3.PanelOverride = dimLine;
        SepBottom.PanelOverride = dimLine;
    }

    private void WireButtons()
    {
        EjectBeakerButton.OnPressed += _ => OnAutodocButton?.Invoke(AutodocUiButton.EjectBeaker);
        EjectPatientButton.OnPressed += _ => OnAutodocButton?.Invoke(AutodocUiButton.EjectPatient);
        StartTreatmentButton.OnPressed += _ => OnAutodocButton?.Invoke(AutodocUiButton.StartTreatment);
    }

    private void SetInitialButtonStates()
    {
        EjectBeakerButton.Disabled = true;
        EjectPatientButton.Disabled = true;
        StartTreatmentButton.Disabled = true;

        EjectBeakerButton.ModulateSelfOverride = ColorInactive;
        EjectPatientButton.ModulateSelfOverride = ColorInactive;
        StartTreatmentButton.ModulateSelfOverride = ColorInactive;
    }

    public void UpdateState(AutodocBoundUserInterfaceState state)
    {
        _sawmill.Debug($"=== UpdateState CALLED === HasBeaker={state.HasBeaker}, HasOccupant={state.HasOccupant}, IsTreating={state.IsTreating}");

        UpdatePatientInfo(state);
        UpdateDamageDisplay(state);
        UpdateStimulantsDisplay(state);
        UpdateButtonsState(state);
        UpdateProgressDisplay(state);
        UpdateErrorDisplay(state);
        UpdateFooter(state);

        _sawmill.Debug("=== UpdateState FINISHED ===");
    }

    private void UpdatePatientInfo(AutodocBoundUserInterfaceState state)
    {
        if (state.HasOccupant && !string.IsNullOrEmpty(state.OccupantName))
        {
            PatientNameLabel.Text = state.OccupantName.ToUpperInvariant();
            PatientNameLabel.FontColorOverride = ColorActive;

            var statusText = state.OccStatus switch
            {
                OccupantStatus.Alive => "VITAL SIGNS: STABLE",
                OccupantStatus.Critical => "VITAL SIGNS: CRITICAL",
                OccupantStatus.Dead => "VITAL SIGNS: NONE - DECEASED",
                _ => "STATUS: UNKNOWN"
            };

            StatusLabel.Text = statusText;
            StatusLabel.FontColorOverride = state.OccStatus switch
            {
                OccupantStatus.Alive => ColorMinor,
                OccupantStatus.Critical => ColorModerate,
                OccupantStatus.Dead => ColorCritical,
                _ => ColorDim
            };
        }
        else
        {
            PatientNameLabel.Text = "NO PATIENT";
            PatientNameLabel.FontColorOverride = ColorDim;
            StatusLabel.Text = "AWAITING SUBJECT";
            StatusLabel.FontColorOverride = ColorDim;
        }
    }

    private void UpdateDamageDisplay(AutodocBoundUserInterfaceState state)
    {
        DamageContainer.RemoveAllChildren();

        if (!state.HasOccupant || state.OccupantDamage == null || state.OccupantDamage.Count == 0)
        {
            var emptyLabel = MakeDiagnosticLine("NO DAMAGE DETECTED", ColorDim);
            DamageContainer.AddChild(emptyLabel);
            return;
        }

        var sortedDamage = state.OccupantDamage
            .OrderByDescending(x => x.Value.Float())
            .ToList();

        foreach (var kvp in sortedDamage)
        {
            var damageType = kvp.Key;
            var amount = kvp.Value;

            if (amount <= 0) continue;

            var displayName = _damageDisplayNames.GetValueOrDefault(damageType, damageType.ToUpperInvariant());
            var color = GetDamageColor(amount.Float());

            DamageContainer.AddChild(MakeDamageLine(displayName, amount.Float(), color));
        }
    }

    private BoxContainer MakeDamageLine(string damageName, float amount, Color color)
    {
        var container = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            SeparationOverride = 8,
            HorizontalExpand = true,
            Margin = new Thickness(0, 2, 0, 2)
        };

        var nameLabel = new Label
        {
            Text = $"[ {damageName} ]",
            FontColorOverride = color,
            StyleClasses = { "monospace" },
            MinWidth = 140
        };

        var barBg = new PanelContainer
        {
            MinWidth = 120,
            MinHeight = 12,
            HorizontalExpand = false,
            PanelOverride = new StyleBoxFlat(Color.FromHex("#1a3a1a"))
        };

        var barWidth = 120f * Math.Clamp(amount / 100f, 0.05f, 1f);
        var fillPanel = new PanelContainer
        {
            MinWidth = barWidth,
            MinHeight = 12,
            PanelOverride = new StyleBoxFlat(color)
        };
        barBg.AddChild(fillPanel);

        var amountLabel = new Label
        {
            Text = $"{amount:F0}%",
            FontColorOverride = color,
            StyleClasses = { "monospace" },
            MinWidth = 50,
            HorizontalAlignment = HAlignment.Right
        };

        container.AddChild(nameLabel);
        container.AddChild(barBg);
        container.AddChild(amountLabel);

        return container;
    }

    private Label MakeDiagnosticLine(string text, Color color)
    {
        return new Label
        {
            Text = text,
            FontColorOverride = color,
            StyleClasses = { "monospace" },
            HorizontalAlignment = HAlignment.Center,
            Margin = new Thickness(0, 8, 0, 8)
        };
    }

    private Color GetDamageColor(float amount)
    {
        if (amount >= 75) return ColorCritical;
        if (amount >= 50) return ColorSevere;
        if (amount >= 25) return ColorModerate;
        if (amount > 0) return ColorMinor;
        return ColorDim;
    }

    private void UpdateStimulantsDisplay(AutodocBoundUserInterfaceState state)
    {
        if (state.HasBeaker)
        {
            var amount = state.BeakerStimulantsAmount.Float();
            StimulantsLabel.Text = $"{amount:F1}";
            StimulantsLabel.FontColorOverride = amount >= 30 ? ColorMinor : ColorModerate;
        }
        else
        {
            StimulantsLabel.Text = "NONE";
            StimulantsLabel.FontColorOverride = ColorDim;
        }
    }

    private void UpdateButtonsState(AutodocBoundUserInterfaceState state)
    {
        var ejectBeakerDisabled = !state.HasBeaker || state.IsTreating;
        var ejectPatientDisabled = !state.HasOccupant || state.IsTreating;
        var startDisabled = !state.TreatButtonEnabled || state.IsTreating;

        EjectBeakerButton.Disabled = ejectBeakerDisabled;
        EjectPatientButton.Disabled = ejectPatientDisabled;
        StartTreatmentButton.Disabled = startDisabled;

        EjectBeakerButton.ModulateSelfOverride = ejectBeakerDisabled ? ColorInactive : null;
        EjectPatientButton.ModulateSelfOverride = ejectPatientDisabled ? ColorInactive : null;
        StartTreatmentButton.ModulateSelfOverride = startDisabled ? ColorInactive : null;

        StartTreatmentButton.Text = state.IsTreating ? "TREATMENT IN PROGRESS" : "START TREATMENT";

        ProgressContainer.Visible = state.IsTreating;
    }

    private void UpdateProgressDisplay(AutodocBoundUserInterfaceState state)
    {
        if (state.IsTreating && state.TreatmentProgress > 0)
        {
            TreatmentProgress.Value = state.TreatmentProgress * 100;
            ProgressPercentLabel.Text = $"{state.TreatmentProgress * 100:F0}%";
        }
        else
        {
            TreatmentProgress.Value = 0;
            ProgressPercentLabel.Text = "0%";
        }
    }

    private void UpdateErrorDisplay(AutodocBoundUserInterfaceState state)
    {
        var hasError = !string.IsNullOrEmpty(state.ErrorMessage);
        ErrorLabel.Visible = hasError;

        if (hasError && state.ErrorMessage != null)
        {
            ErrorLabel.Text = state.ErrorMessage.ToUpperInvariant();
        }
    }

    private void UpdateFooter(AutodocBoundUserInterfaceState state)
    {
        if (state.IsTreating)
        {
            FooterLabel.Text = "[ TREATMENT IN PROGRESS ]";
            FooterLabel.FontColorOverride = ColorModerate;
        }
        else if (!state.Powered)
        {
            FooterLabel.Text = "[ NO POWER ]";
            FooterLabel.FontColorOverride = ColorCritical;
        }
        else if (state.HasOccupant && !state.TreatButtonEnabled)
        {
            FooterLabel.Text = "[ INSUFFICIENT STIMULANTS ]";
            FooterLabel.FontColorOverride = ColorModerate;
        }
        else if (state.HasOccupant)
        {
            FooterLabel.Text = "[ SYSTEM READY ]";
            FooterLabel.FontColorOverride = ColorMinor;
        }
        else
        {
            FooterLabel.Text = "[ SYSTEM READY ]";
            FooterLabel.FontColorOverride = ColorDim;
        }
    }
}
